/*

 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator_package;

import java.awt.Color;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Ateeq
 */
public class Calculator_form extends javax.swing.JFrame {
    Double n1, n2,result;
    char op;
    /**
     * Creates new form Calculator_form
     */
    public Calculator_form() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        TextField.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField = new javax.swing.JTextField();
        TextField2 = new javax.swing.JTextField();
        TextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnplus = new javax.swing.JButton();
        btn_ClrAll = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btnequal = new javax.swing.JButton();
        btnfactorial = new javax.swing.JButton();
        btnminus = new javax.swing.JButton();
        btnmultiply = new javax.swing.JButton();
        btn_divide = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btndot = new javax.swing.JButton();
        btnPower = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        OptionsMenu = new javax.swing.JMenu();
        NewSubMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        TemperatureSubMenu = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        AboutSubMenu = new javax.swing.JMenuItem();
        ExitSubMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculator_practice");
        setBackground(new java.awt.Color(0, 0, 0));

        TextField.setEditable(false);
        TextField.setBackground(new java.awt.Color(241, 249, 184));
        TextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldActionPerformed(evt);
            }
        });

        TextField2.setEditable(false);
        TextField2.setBackground(new java.awt.Color(255, 255, 204));
        TextField2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField2ActionPerformed(evt);
            }
        });

        TextField3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TextField3.setBorder(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("DialogInput", 3, 36)); // NOI18N
        jLabel1.setText("Standard Calculator");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn1.setBackground(new java.awt.Color(255, 255, 204));
        btn1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 255, 204));
        btn2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 255, 204));
        btn3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnplus.setBackground(new java.awt.Color(255, 255, 204));
        btnplus.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnplus.setText("+");
        btnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplusActionPerformed(evt);
            }
        });

        btn_ClrAll.setBackground(new java.awt.Color(255, 255, 204));
        btn_ClrAll.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_ClrAll.setText("ClrAll");
        btn_ClrAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClrAllActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 255, 204));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btnequal.setBackground(new java.awt.Color(255, 255, 204));
        btnequal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnequal.setText("=");
        btnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequalActionPerformed(evt);
            }
        });

        btnfactorial.setBackground(new java.awt.Color(255, 255, 204));
        btnfactorial.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        btnfactorial.setText("!");
        btnfactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfactorialActionPerformed(evt);
            }
        });

        btnminus.setBackground(new java.awt.Color(255, 255, 204));
        btnminus.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnminus.setText("-");
        btnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminusActionPerformed(evt);
            }
        });

        btnmultiply.setBackground(new java.awt.Color(255, 255, 204));
        btnmultiply.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnmultiply.setText("x");
        btnmultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplyActionPerformed(evt);
            }
        });

        btn_divide.setBackground(new java.awt.Color(255, 255, 204));
        btn_divide.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_divide.setText("/");
        btn_divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divideActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(255, 255, 204));
        btn6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(255, 255, 204));
        btn4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(255, 255, 204));
        btn5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(255, 255, 204));
        btn7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(255, 255, 204));
        btn8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(255, 255, 204));
        btn9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn9.setText("9");
        btn9.setMaximumSize(new java.awt.Dimension(33, 33));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(255, 255, 204));
        btn0.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btndot.setBackground(new java.awt.Color(255, 255, 204));
        btndot.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btndot.setText(".");
        btndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotActionPerformed(evt);
            }
        });

        btnPower.setBackground(new java.awt.Color(255, 255, 204));
        btnPower.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        btnPower.setText("Power");
        btnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndot, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPower, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_divide, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnminus, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnequal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(btn_ClrAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnfactorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ClrAll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnminus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnequal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnfactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_divide, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPower, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btndot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, 0))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("History");

        TextArea1.setEditable(false);
        TextArea1.setColumns(20);
        TextArea1.setRows(5);
        TextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane1.setViewportView(TextArea1);

        OptionsMenu.setText("Options");

        NewSubMenu.setText("New Window");
        NewSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSubMenuActionPerformed(evt);
            }
        });
        OptionsMenu.add(NewSubMenu);
        OptionsMenu.add(jSeparator1);

        TemperatureSubMenu.setText("Temperature converter");
        OptionsMenu.add(TemperatureSubMenu);

        jMenuBar1.add(OptionsMenu);

        HelpMenu.setText("Help");

        AboutSubMenu.setText("About");
        AboutSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutSubMenuActionPerformed(evt);
            }
        });
        HelpMenu.add(AboutSubMenu);

        ExitSubMenu.setText("Exit");
        ExitSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitSubMenuActionPerformed(evt);
            }
        });
        HelpMenu.add(ExitSubMenu);

        jMenuBar1.add(HelpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(180, 180, 180)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(273, 273, 273))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(461, 461, 461)
                .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldActionPerformed

    private void btnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequalActionPerformed
        // TODO add your handling code here:
    try {
        TextArea1.setText(TextArea1.getText() + TextField2.getText() + " = " + TextField3.getText() + "    \n");
        TextField2.setText(TextField3.getText());
}  
    catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid input: " + e.getMessage());
    }
    catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnequalActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if(TextField2.getText().isBlank()){
        TextField.setText(TextField.getText() + "1");
        TextField2.setText(TextField2.getText() + "1");
        }
        else{
            int counter = 0;
            String str = TextField2.getText();
            char[] arr = str.toCharArray();
            for(char c: arr){
                if(c == '+'||c == '-' ||c == '*'||c == '/'||c == '^'){
                    counter++;
                }
            }
        if(counter == 0 || (arr.length == 1) ){
            TextField.setText(TextField.getText() + "1");
        TextField2.setText(TextField2.getText() + "1");
        }
        else{
            try {
                TextField.setText(TextField.getText() +"1");
        TextField2.setText(TextField2.getText() + "1");
        n2 = Double.parseDouble(TextField.getText());
        switch (op) {
    case '+'-> {
        result = n1 + n2;
        TextField3.setText(String.valueOf(result));
    }
    case '-'->{
        result = n1 - n2;
        TextField3.setText(String.valueOf(result));

    }
    case '*'->{
        result = n1 * n2;
        TextField3.setText(String.valueOf(result));
    }
    case '/'->{ 
    if(n2 != 0){
        result = n1 / n2;
        TextField3.setText(String.valueOf(result));

    }
    else{
        JOptionPane.showMessageDialog(this, "Division by zero is not allowed");
    }
      }
    case '^' ->{
       double result = 1L;
    if(n2 == 0){
        TextField3.setText("0");

    }
    else if(n2 < 0){
    n2 = (-1*n2);
    for(int i = 1; i <= n2; i++){
      result = result * n1;
    }
    TextField3.setText(String.valueOf(1/result));
    
    }
    else if(n2 > 0){
    for(int i = 1; i <= n2; i++){
     result = result * n1;
    }
    TextField3.setText(String.valueOf(result));
      }
     }
    }
}  
    catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid input: " + e.getMessage());
    }
    catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        }
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if(TextField2.getText().isBlank()){
        TextField.setText(TextField.getText() + "2");
        TextField2.setText(TextField2.getText() + "2");
        }
        else{
            int counter = 0;
            String str = TextField2.getText();
            char[] arr = str.toCharArray();
            for(char c: arr){
                if(c == '+'||c == '-' ||c == '*'||c == '/'||c == '^'){
                    counter++;
                }
            }
        if(counter == 0 || (arr.length == 1) ){
            TextField.setText(TextField.getText() + "2");
        TextField2.setText(TextField2.getText() + "2");
        }
        else{
            try {
                TextField.setText(TextField.getText() +"2");
        TextField2.setText(TextField2.getText() + "2");
        n2 = Double.parseDouble(TextField.getText());
        switch (op) {
    case '+'-> {
        result = n1 + n2;
        TextField3.setText(String.valueOf(result));
    }
    case '-'->{
        result = n1 - n2;
        TextField3.setText(String.valueOf(result));

    }
    case '*'->{
        result = n1 * n2;
        TextField3.setText(String.valueOf(result));
    }
    case '/'->{ 
    if(n2 != 0){
        result = n1 / n2;
        TextField3.setText(String.valueOf(result));

    }
    else{
        JOptionPane.showMessageDialog(this, "Division by zero is not allowed");
    }
      }
    case '^' ->{
       double result = 1L;
    if(n2 == 0){
        TextField3.setText("0");

    }
    else if(n2 < 0){
    n2 = (-1*n2);
    for(int i = 1; i <= n2; i++){
      result = result * n1;
    }
    TextField3.setText(String.valueOf(1/result));
    
    }
    else if(n2 > 0){
    for(int i = 1; i <= n2; i++){
     result = result * n1;
    }
    TextField3.setText(String.valueOf(result));
      }
     }
    }
}  
    catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid input: " + e.getMessage());
    }
    catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        }
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplusActionPerformed
        // TODO add your handling code here:
        try{
            if(TextField3.getText().isBlank()){
        n1 = Double.parseDouble(TextField.getText());
        op = '+';
        TextField.setText("");
        TextField2.setText(TextField2.getText() + "+");
        }
            else{
                n1 = Double.parseDouble(TextField3.getText());
                op = '+';
                TextField.setText("");
                TextField2.setText(TextField2.getText() + "+");
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Invalid input");
        }
    }//GEN-LAST:event_btnplusActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if(TextField2.getText().isBlank()){
        TextField.setText(TextField.getText() + "3");
        TextField2.setText(TextField2.getText() + "3");
        }
        else{
            int counter = 0;
            String str = TextField2.getText();
            char[] arr = str.toCharArray();
            for(char c: arr){
                if(c == '+'||c == '-' ||c == '*'||c == '/'||c == '^'){
                    counter++;
                }
            }
        if(counter == 0 || (arr.length == 1) ){
            TextField.setText(TextField.getText() + "3");
        TextField2.setText(TextField2.getText() + "3");
        }
        else{
            try {
                TextField.setText(TextField.getText() +"3");
        TextField2.setText(TextField2.getText() + "3");
        n2 = Double.parseDouble(TextField.getText());
        switch (op) {
    case '+'-> {
        result = n1 + n2;
        TextField3.setText(String.valueOf(result));
    }
    case '-'->{
        result = n1 - n2;
        TextField3.setText(String.valueOf(result));

    }
    case '*'->{
        result = n1 * n2;
        TextField3.setText(String.valueOf(result));
    }
    case '/'->{ 
    if(n2 != 0){
        result = n1 / n2;
        TextField3.setText(String.valueOf(result));

    }
    else{
        JOptionPane.showMessageDialog(this, "Division by zero is not allowed");
    }
      }
    case '^' ->{
       double result = 1L;
    if(n2 == 0){
        TextField3.setText("0");

    }
    else if(n2 < 0){
    n2 = (-1*n2);
    for(int i = 1; i <= n2; i++){
      result = result * n1;
    }
    TextField3.setText(String.valueOf(1/result));
    
    }
    else if(n2 > 0){
    for(int i = 1; i <= n2; i++){
     result = result * n1;
    }
    TextField3.setText(String.valueOf(result));
      }
     }
    }
}  
    catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid input: " + e.getMessage());
    }
    catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        }
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if(TextField2.getText().isBlank()){
        TextField.setText(TextField.getText() + "4");
        TextField2.setText(TextField2.getText() + "4");
        }
        else{
            int counter = 0;
            String str = TextField2.getText();
            char[] arr = str.toCharArray();
            for(char c: arr){
                if(c == '+'||c == '-' ||c == '*'||c == '/'||c == '^'){
                    counter++;
                }
            }
        if(counter == 0 || (arr.length == 1) ){
            TextField.setText(TextField.getText() + "4");
        TextField2.setText(TextField2.getText() + "4");
        }
        else{
            try {
                TextField.setText(TextField.getText() +"4");
        TextField2.setText(TextField2.getText() + "4");
        n2 = Double.parseDouble(TextField.getText());
        switch (op) {
    case '+'-> {
        result = n1 + n2;
        TextField3.setText(String.valueOf(result));
    }
    case '-'->{
        result = n1 - n2;
        TextField3.setText(String.valueOf(result));

    }
    case '*'->{
        result = n1 * n2;
        TextField3.setText(String.valueOf(result));
    }
    case '/'->{ 
    if(n2 != 0){
        result = n1 / n2;
        TextField3.setText(String.valueOf(result));

    }
    else{
        JOptionPane.showMessageDialog(this, "Division by zero is not allowed");
    }
      }
    case '^' ->{
       double result = 1L;
    if(n2 == 0){
        TextField3.setText("0");

    }
    else if(n2 < 0){
    n2 = (-1*n2);
    for(int i = 1; i <= n2; i++){
      result = result * n1;
    }
    TextField3.setText(String.valueOf(1/result));
    
    }
    else if(n2 > 0){
    for(int i = 1; i <= n2; i++){
     result = result * n1;
    }
    TextField3.setText(String.valueOf(result));
      }
     }
    }
}  
    catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid input: " + e.getMessage());
    }
    catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        }
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if(TextField2.getText().isBlank()){
        TextField.setText(TextField.getText() + "5");
        TextField2.setText(TextField2.getText() + "5");
        }
        else{
            int counter = 0;
            String str = TextField2.getText();
            char[] arr = str.toCharArray();
            for(char c: arr){
                if(c == '+'||c == '-' ||c == '*'||c == '/'||c == '^'){
                    counter++;
                }
            }
        if(counter == 0){
            TextField.setText(TextField.getText() + "5");
        TextField2.setText(TextField2.getText() + "5");
        }
        else{
            try {
                TextField.setText(TextField.getText() +"5");
        TextField2.setText(TextField2.getText() + "5");
        n2 = Double.parseDouble(TextField.getText());
        switch (op) {
    case '+'-> {
        result = n1 + n2;
        TextField3.setText(String.valueOf(result));
    }
    case '-'->{
        result = n1 - n2;
        TextField3.setText(String.valueOf(result));

    }
    case '*'->{
        result = n1 * n2;
        TextField3.setText(String.valueOf(result));
    }
    case '/'->{ 
    if(n2 != 0){
        result = n1 / n2;
        TextField3.setText(String.valueOf(result));

    }
    else{
        JOptionPane.showMessageDialog(this, "Division by zero is not allowed");
    }
      }
    case '^' ->{
       double result = 1L;
    if(n2 == 0){
        TextField3.setText("0");

    }
    else if(n2 < 0){
    n2 = (-1*n2);
    for(int i = 1; i <= n2; i++){
      result = result * n1;
    }
    TextField3.setText(String.valueOf(1/result));
    
    }
    else if(n2 > 0){
    for(int i = 1; i <= n2; i++){
     result = result * n1;
    }
    TextField3.setText(String.valueOf(result));
      }
     }
    }
}  
    catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid input: " + e.getMessage());
    }
    catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        }
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if(TextField2.getText().isBlank()){
        TextField.setText(TextField.getText() + "6");
        TextField2.setText(TextField2.getText() + "6");
        }
        else{
            int counter = 0;
            String str = TextField2.getText();
            char[] arr = str.toCharArray();
            for(char c: arr){
                if(c == '+'||c == '-' ||c == '*'||c == '/'||c == '^'){
                    counter++;
                }
            }
        if(counter == 0 || (arr.length == 1) ){
            TextField.setText(TextField.getText() + "6");
        TextField2.setText(TextField2.getText() + "6");
        }
        else{
            try {
                TextField.setText(TextField.getText() +"6");
        TextField2.setText(TextField2.getText() + "6");
        n2 = Double.parseDouble(TextField.getText());
        switch (op) {
    case '+'-> {
        result = n1 + n2;
        TextField3.setText(String.valueOf(result));
    }
    case '-'->{
        result = n1 - n2;
        TextField3.setText(String.valueOf(result));

    }
    case '*'->{
        result = n1 * n2;
        TextField3.setText(String.valueOf(result));
    }
    case '/'->{ 
    if(n2 != 0){
        result = n1 / n2;
        TextField3.setText(String.valueOf(result));

    }
    else{
        JOptionPane.showMessageDialog(this, "Division by zero is not allowed");
    }
      }
    case '^' ->{
       double result = 1L;
    if(n2 == 0){
        TextField3.setText("0");

    }
    else if(n2 < 0){
    n2 = (-1*n2);
    for(int i = 1; i <= n2; i++){
      result = result * n1;
    }
    TextField3.setText(String.valueOf(1/result));
    
    }
    else if(n2 > 0){
    for(int i = 1; i <= n2; i++){
     result = result * n1;
    }
    TextField3.setText(String.valueOf(result));
      }
     }
    }
}  
    catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid input: " + e.getMessage());
    }
    catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        }
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if(TextField2.getText().isBlank()){
        TextField.setText(TextField.getText() + "7");
        TextField2.setText(TextField2.getText() + "7");
        }
        else{
            int counter = 0;
            String str = TextField2.getText();
            char[] arr = str.toCharArray();
            for(char c: arr){
                if(c == '+'||c == '-' ||c == '*'||c == '/'||c == '^'){
                    counter++;
                }
            }
        if(counter == 0 || (arr.length == 1) ){
            TextField.setText(TextField.getText() + "7");
        TextField2.setText(TextField2.getText() + "7");
        }
        else{
            try {
                TextField.setText(TextField.getText() +"7");
        TextField2.setText(TextField2.getText() + "7");
        n2 = Double.parseDouble(TextField.getText());
        switch (op) {
    case '+'-> {
        result = n1 + n2;
        TextField3.setText(String.valueOf(result));
    }
    case '-'->{
        result = n1 - n2;
        TextField3.setText(String.valueOf(result));

    }
    case '*'->{
        result = n1 * n2;
        TextField3.setText(String.valueOf(result));
    }
    case '/'->{ 
    if(n2 != 0){
        result = n1 / n2;
        TextField3.setText(String.valueOf(result));

    }
    else{
        JOptionPane.showMessageDialog(this, "Division by zero is not allowed");
    }
      }
    case '^' ->{
       double result = 1L;
    if(n2 == 0){
        TextField3.setText("0");

    }
    else if(n2 < 0){
    n2 = (-1*n2);
    for(int i = 1; i <= n2; i++){
      result = result * n1;
    }
    TextField3.setText(String.valueOf(1/result));
    
    }
    else if(n2 > 0){
    for(int i = 1; i <= n2; i++){
     result = result * n1;
    }
    TextField3.setText(String.valueOf(result));
      }
     }
    }
}  
    catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid input: " + e.getMessage());
    }
    catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        }
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if(TextField2.getText().isBlank()){
        TextField.setText(TextField.getText() + "8");
        TextField2.setText(TextField2.getText() + "8");
        }
        else{
            int counter = 0;
            String str = TextField2.getText();
            char[] arr = str.toCharArray();
            for(char c: arr){
                if(c == '+'||c == '-' ||c == '*'||c == '/'||c == '^'){
                    counter++;
                }
            }
        if(counter == 0 || (arr.length == 1) ){
            TextField.setText(TextField.getText() + "8");
        TextField2.setText(TextField2.getText() + "8");
        }
        else{
            try {
                TextField.setText(TextField.getText() +"8");
        TextField2.setText(TextField2.getText() + "8");
        n2 = Double.parseDouble(TextField.getText());
        switch (op) {
    case '+'-> {
        result = n1 + n2;
        TextField3.setText(String.valueOf(result));
    }
    case '-'->{
        result = n1 - n2;
        TextField3.setText(String.valueOf(result));

    }
    case '*'->{
        result = n1 * n2;
        TextField3.setText(String.valueOf(result));
    }
    case '/'->{ 
    if(n2 != 0){
        result = n1 / n2;
        TextField3.setText(String.valueOf(result));

    }
    else{
        JOptionPane.showMessageDialog(this, "Division by zero is not allowed");
    }
      }
    case '^' ->{
       double result = 1L;
    if(n2 == 0){
        TextField3.setText("0");

    }
    else if(n2 < 0){
    n2 = (-1*n2);
    for(int i = 1; i <= n2; i++){
      result = result * n1;
    }
    TextField3.setText(String.valueOf(1/result));
    
    }
    else if(n2 > 0){
    for(int i = 1; i <= n2; i++){
     result = result * n1;
    }
    TextField3.setText(String.valueOf(result));
      }
     }
    }
}  
    catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid input: " + e.getMessage());
    }
    catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        }
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if(TextField2.getText().isBlank()){
        TextField.setText(TextField.getText() + "9");
        TextField2.setText(TextField2.getText() + "9");
        }
        else{
            int counter = 0;
            String str = TextField2.getText();
            char[] arr = str.toCharArray();
            for(char c: arr){
                if(c == '+'||c == '-' ||c == '*'||c == '/'||c == '^'){
                    counter++;
                }
            }
        if(counter == 0 || (arr.length == 1) ){
            TextField.setText(TextField.getText() + "0");
        TextField2.setText(TextField2.getText() + "0");
        }
        else{
            try {
                TextField.setText(TextField.getText() +"9");
        TextField2.setText(TextField2.getText() + "9");
        n2 = Double.parseDouble(TextField.getText());
        switch (op) {
    case '+'-> {
        result = n1 + n2;
        TextField3.setText(String.valueOf(result));
    }
    case '-'->{
        result = n1 - n2;
        TextField3.setText(String.valueOf(result));

    }
    case '*'->{
        result = n1 * n2;
        TextField3.setText(String.valueOf(result));
    }
    case '/'->{ 
    if(n2 != 0){
        result = n1 / n2;
        TextField3.setText(String.valueOf(result));

    }
    else{
        JOptionPane.showMessageDialog(this, "Division by zero is not allowed");
    }
      }
    case '^' ->{
       double result = 1L;
    if(n2 == 0){
        TextField3.setText("0");

    }
    else if(n2 < 0){
    n2 = (-1*n2);
    for(int i = 1; i <= n2; i++){
      result = result * n1;
    }
    TextField3.setText(String.valueOf(1/result));
    
    }
    else if(n2 > 0){
    for(int i = 1; i <= n2; i++){
     result = result * n1;
    }
    TextField3.setText(String.valueOf(result));
      }
     }
    }
}  
    catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid input: " + e.getMessage());
    }
    catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        }
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        if(TextField2.getText().isBlank()){
        TextField.setText(TextField.getText() + "0");
        TextField2.setText(TextField2.getText() + "0");
        }
        else{
            int counter = 0;
            String str = TextField2.getText();
            char[] arr = str.toCharArray();
            for(char c: arr){
                if(c == '+'||c == '-' ||c == '*'||c == '/'||c == '^'){
                    counter++;
                }
            }
        if(counter == 0){
            TextField.setText(TextField.getText() + "0");
        TextField2.setText(TextField2.getText() + "0");
        }
        else{
            try {
                TextField.setText(TextField.getText() +"0");
        TextField2.setText(TextField2.getText() + "0");
        n2 = Double.parseDouble(TextField.getText());
        switch (op) {
    case '+'-> {
        result = n1 + n2;
        TextField3.setText(String.valueOf(result));
    }
    case '-'->{
        result = n1 - n2;
        TextField3.setText(String.valueOf(result));

    }
    case '*'->{
        result = n1 * n2;
        TextField3.setText(String.valueOf(result));
    }
    case '/'->{ 
    if(n2 != 0){
        result = n1 / n2;
        TextField3.setText(String.valueOf(result));

    }
    else{
        JOptionPane.showMessageDialog(this, "Division by zero is not allowed");
    }
      }
    case '^' ->{
       double result = 1L;
    if(n2 == 0){
        TextField3.setText("0");

    }
    else if(n2 < 0){
    n2 = (-1*n2);
    for(int i = 1; i <= n2; i++){
      result = result * n1;
    }
    TextField3.setText(String.valueOf(1/result));
    
    }
    else if(n2 > 0){
    for(int i = 1; i <= n2; i++){
     result = result * n1;
    }
    TextField3.setText(String.valueOf(result));
      }
     }
    }
}  
    catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid input: " + e.getMessage());
    }
    catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        }
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndotActionPerformed
        // TODO add your handling code here:
        TextField.setText(TextField.getText() + ".");
        TextField2.setText(TextField2.getText() + ".");
    }//GEN-LAST:event_btndotActionPerformed

    private void btnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminusActionPerformed
        // TODO add your handling code here;
        try{
            if(TextField2.getText().isBlank()){
                TextField.setText("-");
                TextField2.setText("-");
            }
            else{
        String str;
            str = TextField2.getText();
        char[] arr = str.toCharArray();
        int length = arr.length;
        length = length - 1;
            switch (arr[length]) {
                case '-' -> {
                    op = '+';
                    TextField2.setText(TextField2.getText() + "-");
                }
                case '+' -> {
                    op = '-';
                    TextField2.setText(TextField2.getText() + "-");
                }
                case '*' -> {
                    TextField.setText("-");
                    TextField2.setText(TextField2.getText() + "-");
                }
                case '/' -> {
                    TextField.setText("-");
                    TextField2.setText(TextField2.getText() + "-");
                }
                case '^' ->{
                    TextField.setText("-");
                    TextField2.setText(TextField2.getText() + "-");
                }
                default -> {
                    if(TextField3.getText().isBlank()){
                    n1 = Double.parseDouble(TextField.getText());
                    op = '-';
                    TextField.setText("");
                    TextField2.setText(TextField2.getText() + "-");
                    }
                    else{
                        n1 = Double.parseDouble(TextField3.getText());
                    op = '-';
                    TextField.setText("");
                    TextField2.setText(TextField2.getText() + "-");
                    }
                }
            }
        }
}
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Invalid input");
        }
    }//GEN-LAST:event_btnminusActionPerformed

    private void btnmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplyActionPerformed
        // TODO add your handling code here
        try{
            if(TextField3.getText().isBlank()){
        n1 = Double.parseDouble(TextField.getText());
        op = '*';
        TextField.setText("");
        TextField2.setText(TextField2.getText() + "*");
        }
            else{
                n1 = Double.parseDouble(TextField3.getText());
                op = '*';
                TextField.setText("");
                TextField2.setText(TextField2.getText() + "*");
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Invalid input");
        }
    }//GEN-LAST:event_btnmultiplyActionPerformed

    private void btn_divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divideActionPerformed
        // TODO add your handling code here
        try{
            if(TextField3.getText().isBlank()){
        n1 = Double.parseDouble(TextField.getText());
        op = '/';
        TextField.setText("");
        TextField2.setText(TextField2.getText() + "/");
        }
            else{
                n1 = Double.parseDouble(TextField3.getText());
                op = '/';
                TextField.setText("");
                TextField2.setText(TextField2.getText() + "/");
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Invalid input");
        }
    }//GEN-LAST:event_btn_divideActionPerformed

    private void btn_ClrAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClrAllActionPerformed
        // TODO add your handling code here:
        TextField.setText("");
        TextField2.setText("");
        TextField3.setText("");
    }//GEN-LAST:event_btn_ClrAllActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void TextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextField2ActionPerformed

    private void NewSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSubMenuActionPerformed
        // TODO add your handling code here:
        new Calculator_form().setVisible(true);
    }//GEN-LAST:event_NewSubMenuActionPerformed

    private void AboutSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutSubMenuActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
    }//GEN-LAST:event_AboutSubMenuActionPerformed

    private void ExitSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitSubMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitSubMenuActionPerformed

    private void btnfactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfactorialActionPerformed
        // TODO add your handling code here:
        Long number1 = Long.parseLong(TextField.getText());
        if(number1 >= 0){
        TextField2.setText(TextField2.getText() + "!");
        Long fact = 1L;
    for(Long i = number1; i >= 1; i--){
     fact = fact * i;
    }
    TextField.setText(String.valueOf(fact));
    TextField3.setText(String.valueOf(fact));
        }
        else{
            JOptionPane.showMessageDialog(this, "Factorial is not for negative numbers, Pleas give a non-negative number");
        }
    }//GEN-LAST:event_btnfactorialActionPerformed

    private void btnPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerActionPerformed
        // TODO add your handling code here:
        try{
        n1 = Double.parseDouble(TextField.getText());
        op = '^';
        TextField.setText("");
        TextField2.setText(TextField2.getText() + "^");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Invalid input");
        }
    }//GEN-LAST:event_btnPowerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutSubMenu;
    private javax.swing.JMenuItem ExitSubMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JMenuItem NewSubMenu;
    private javax.swing.JMenu OptionsMenu;
    private javax.swing.JMenuItem TemperatureSubMenu;
    private javax.swing.JTextArea TextArea1;
    private javax.swing.JTextField TextField;
    private javax.swing.JTextField TextField2;
    private javax.swing.JTextField TextField3;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btn_ClrAll;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_divide;
    private javax.swing.JButton btndot;
    private javax.swing.JButton btnequal;
    private javax.swing.JButton btnfactorial;
    private javax.swing.JButton btnminus;
    private javax.swing.JButton btnmultiply;
    private javax.swing.JButton btnplus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables


}
