/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator_package;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Muhammad Ateeq
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form Temperature_form
     */
    public MainForm() {
        initComponents();
          //set Full size
        setExtendedState(JFrame.MAXIMIZED_BOTH);
          //Make Objects of CalculatorForm and About Form
        Calculator_form calculatorForm = new Calculator_form();
        About aboutForm = new About();
        TemperatureForm tempForm = new TemperatureForm();
          //Remove the content pane's layout manager
        calculatorForm.getContentPane().setLayout(null);
        aboutForm.getContentPane().setLayout(null);
        tempForm.getContentPane().setLayout(null);
          //Get the content Panes
        JPanel calculatorPanel = (JPanel) calculatorForm.getContentPane();
        JPanel aboutPanel = (JPanel) aboutForm.getContentPane();
        JPanel tempPanel  = (JPanel) tempForm.getContentPane();
          //add the Content Panes to the Card Layout
        getContentPane().setLayout(new CardLayout());
        getContentPane().add(calculatorPanel, "Calculator");
        getContentPane().add(aboutPanel, "About");
        getContentPane().add(tempPanel, "Temperature");
          //Show the Calculator Panel by default
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "Calculator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        OptionsMenu = new javax.swing.JMenu();
        MainPageSubMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        NewSubMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        TemperatureSubMenu = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        ExitSubMenu = new javax.swing.JMenuItem();
        CheckerSubMenu = new javax.swing.JMenu();
        PrimecheckerSubMenu = new javax.swing.JMenuItem();
        Armstrongchecker = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        AboutSubMenu2 = new javax.swing.JMenuItem();

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usman Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(new java.awt.CardLayout());

        OptionsMenu.setText("Options");

        MainPageSubMenu.setText("Main Page");
        MainPageSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainPageSubMenuActionPerformed(evt);
            }
        });
        OptionsMenu.add(MainPageSubMenu);
        OptionsMenu.add(jSeparator1);

        NewSubMenu.setText("New Window");
        NewSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSubMenuActionPerformed(evt);
            }
        });
        OptionsMenu.add(NewSubMenu);
        OptionsMenu.add(jSeparator2);

        TemperatureSubMenu.setText("Temperature converter");
        TemperatureSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemperatureSubMenuActionPerformed(evt);
            }
        });
        OptionsMenu.add(TemperatureSubMenu);
        OptionsMenu.add(jSeparator3);

        ExitSubMenu.setText("Exit");
        ExitSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitSubMenuActionPerformed(evt);
            }
        });
        OptionsMenu.add(ExitSubMenu);

        CheckerSubMenu.setText("Checkers");

        PrimecheckerSubMenu.setText("Prime number checker");
        CheckerSubMenu.add(PrimecheckerSubMenu);

        Armstrongchecker.setText("Armstrong number checker");
        CheckerSubMenu.add(Armstrongchecker);

        OptionsMenu.add(CheckerSubMenu);

        jMenuBar1.add(OptionsMenu);

        HelpMenu.setText("Help");

        AboutSubMenu2.setText("About");
        AboutSubMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutSubMenu2ActionPerformed(evt);
            }
        });
        HelpMenu.add(AboutSubMenu2);

        jMenuBar1.add(HelpMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AboutSubMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutSubMenu2ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) getContentPane().getLayout();
        card.show(getContentPane(), "About");
    }//GEN-LAST:event_AboutSubMenu2ActionPerformed

    private void MainPageSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainPageSubMenuActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "Calculator");
    }//GEN-LAST:event_MainPageSubMenuActionPerformed

    private void ExitSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitSubMenuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitSubMenuActionPerformed

    private void NewSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSubMenuActionPerformed
        // TODO add your handling code here:
        new MainForm().setVisible(true);
    }//GEN-LAST:event_NewSubMenuActionPerformed

    private void TemperatureSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemperatureSubMenuActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "Temperature");
    }//GEN-LAST:event_TemperatureSubMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutSubMenu2;
    private javax.swing.JMenuItem Armstrongchecker;
    private javax.swing.JMenu CheckerSubMenu;
    private javax.swing.JMenuItem ExitSubMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JMenuItem MainPageSubMenu;
    private javax.swing.JMenuItem NewSubMenu;
    private javax.swing.JMenu OptionsMenu;
    private javax.swing.JMenuItem PrimecheckerSubMenu;
    private javax.swing.JMenuItem TemperatureSubMenu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
