/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator_package;
import java.awt.Color;
/**
 *
 * @author Muhammad Ateeq
 */
public class TemperatureForm extends javax.swing.JFrame {
    public static double celsiustofahren(double temp){
      temp = (temp * 9.0/5.0) + 32.0;
return temp;
}
    public static double fahrentocelsius(double temp){
      temp = (5.0/9.0) * (temp - 32);
return temp;
}
    public static double celsiustokelvin(double temp){
        temp = temp + 273.15;
        return temp;
    }
    public static double fahrentokelvin(double temp){
        temp = ((5.0/9.0) * (temp-32.0)) + 273.0;
        return temp;
    }
    public static double kelvintocelsius(double temp){
        temp = temp - 273.15;
        return temp;
    }
    public static double kelvintofahren(double temp){
        temp = ((temp - 273.0) * 9.0/5.0) + 32.0;
        return temp;
    }

    /**
     * Creates new form TemperatureForm
     */
    public TemperatureForm() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CelsiusLabel = new javax.swing.JLabel();
        FahrenheitLabel = new javax.swing.JLabel();
        KelvinLabel = new javax.swing.JLabel();
        CelsiusField = new javax.swing.JTextField();
        FahrenheitField = new javax.swing.JTextField();
        KelvinField = new javax.swing.JTextField();
        MainLabelTemperatureForm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1048, 658));

        CelsiusLabel.setBackground(new java.awt.Color(255, 255, 204));
        CelsiusLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CelsiusLabel.setText("Celsius");
        CelsiusLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        FahrenheitLabel.setBackground(new java.awt.Color(255, 255, 204));
        FahrenheitLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FahrenheitLabel.setText("Fahrenheit");
        FahrenheitLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        KelvinLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        KelvinLabel.setText("Kelvin");
        KelvinLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        CelsiusField.setBackground(new java.awt.Color(255, 255, 204));
        CelsiusField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CelsiusField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        CelsiusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelsiusFieldActionPerformed(evt);
            }
        });
        CelsiusField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CelsiusFieldKeyReleased(evt);
            }
        });

        FahrenheitField.setBackground(new java.awt.Color(255, 255, 204));
        FahrenheitField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FahrenheitField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        FahrenheitField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FahrenheitFieldActionPerformed(evt);
            }
        });
        FahrenheitField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FahrenheitFieldKeyReleased(evt);
            }
        });

        KelvinField.setBackground(new java.awt.Color(255, 255, 204));
        KelvinField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        KelvinField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        KelvinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelvinFieldActionPerformed(evt);
            }
        });
        KelvinField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                KelvinFieldKeyReleased(evt);
            }
        });

        MainLabelTemperatureForm.setFont(new java.awt.Font("Bahnschrift", 2, 36)); // NOI18N
        MainLabelTemperatureForm.setText("Temperature Converter");
        MainLabelTemperatureForm.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FahrenheitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KelvinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CelsiusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CelsiusField)
                            .addComponent(FahrenheitField)
                            .addComponent(KelvinField)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(309, Short.MAX_VALUE)
                        .addComponent(MainLabelTemperatureForm)))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(MainLabelTemperatureForm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CelsiusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CelsiusField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FahrenheitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FahrenheitField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KelvinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KelvinField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CelsiusFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CelsiusFieldKeyReleased
        // TODO add your handling code here:
        try{
            double temp1 = Double.parseDouble(CelsiusField.getText());
            FahrenheitField.setText(String.valueOf(celsiustofahren(temp1)));
            KelvinField.setText(String.valueOf(celsiustokelvin(temp1)));
        }
        catch(NumberFormatException e){
            KelvinField.setText("");
            FahrenheitField.setText("");
        }
    }//GEN-LAST:event_CelsiusFieldKeyReleased

    private void FahrenheitFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FahrenheitFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_FahrenheitFieldActionPerformed

    private void KelvinFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelvinFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelvinFieldActionPerformed

    private void FahrenheitFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FahrenheitFieldKeyReleased
        // TODO add your handling code here:
        try{
            Double temp2 = Double.parseDouble(FahrenheitField.getText());
            CelsiusField.setText(String.valueOf(fahrentocelsius(temp2)));
            KelvinField.setText(String.valueOf(fahrentokelvin(temp2)));
        }
        catch(NumberFormatException e){
            KelvinField.setText("");
            CelsiusField.setText("");
        }
    }//GEN-LAST:event_FahrenheitFieldKeyReleased

    private void CelsiusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelsiusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CelsiusFieldActionPerformed

    private void KelvinFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KelvinFieldKeyReleased
        // TODO add your handling code here:
        try{
            Double temp2 = Double.parseDouble(KelvinField.getText());
            CelsiusField.setText(String.valueOf(kelvintocelsius(temp2)));
            FahrenheitField.setText(String.valueOf(kelvintofahren(temp2)));
        }
        catch(NumberFormatException e){
            KelvinField.setText("");
            FahrenheitField.setText("");
        }
    }//GEN-LAST:event_KelvinFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CelsiusField;
    private javax.swing.JLabel CelsiusLabel;
    private javax.swing.JTextField FahrenheitField;
    private javax.swing.JLabel FahrenheitLabel;
    private javax.swing.JTextField KelvinField;
    private javax.swing.JLabel KelvinLabel;
    private javax.swing.JLabel MainLabelTemperatureForm;
    // End of variables declaration//GEN-END:variables
}